### ISSUE TITLE
Group page only shows a subset of hosts

### ISSUE THREAD

**Issue by ShaneSaww** [coreroller/coreroller#60]
It only appears to show 25 hosts at a time, even if the group has more than 25 hosts.

Related to that, is that it would be nice to filter hosts by which version they have inside the group

**Comment by tegioz** [comment]
Thanks for reporting this @ShaneSaww, it should be fixed now.

Regarding the ability to filter instances by version in the group view, all instances in the same group are supposed to have the same version eventually. Also, after one day without requesting updates old instances -potentially running a different version- won't be displayed again. So most of the time the filter won't be of much help, except during a rollout of a new version or while old instances are still around (within the 24hr window). 

If you still think it's something valuable to you please open a new ticket for it :)

**Comment by ShaneSaww** [comment]
@tegioz I would still have a use for the filter view. A big part of that is just to find hosts that aren't updating to the correct version. This can happen when doing something like CoreOS downgrades which require some sort of manual intervention. 

I also wouldn't mind taking a stab at putting a PR together for it, if that works.

**Comment by tegioz** [comment]
I see, makes sense. 

Sure, a PR would be great! Maybe to keep it simple initially the filtering could be done only on the frontend side, similar to the `Search` option in the applications list. Given that there is no pagination yet all data needed should be already downloaded. Some sort of select multiple showing used versions in that group might look nice.

@cynthia-sg will be happy to help about anything related to design / frontend if you need any help.
